---
title: Data Science, Moore's Law, and Moneyball
author: ''
date: '2011-09-27'
slug: data-science-moore-s-law-and-moneyball
categories:
  - professional
tags:
  - analytics
  - data science
  - meetup
---

I'm fond of navel gazing, meta discussions, and so forth. I've recently written about <a title="hacking .gov shortened links" href="http://www.harlan.harris.name/2011/07/hacking-gov-shortened-links/">inferring navel gazing from link data</a>, and about <a title="On “Analytics” and related fields" href="http://www.harlan.harris.name/2011/04/on-analytics-and-related-fields/">the meaning of the "Analytics" buzzword</a>. This post will be <a title="“Data Scientist” and other titles" href="http://www.harlan.harris.name/2011/02/data-scientist-and-other-titles/">my second</a> on that other infectious buzzword, "Data Science".

When I moved to Washington DC in July, I was struck by the fact that there was no <a href="http://www.meetup.com" target="_blank" rel="noopener">Meetup</a> for analytics/applied statistics/machine learning/data science. There's a great <a href="http://www.meetup.com/DC-Tech-Meetup/" target="_blank" rel="noopener">DC Tech Meetup</a>, a great <a href="http://www.meetup.com/bigdatadc/" target="_blank" rel="noopener">Big Data Meetup</a>, and a great <a href="http://www.meetup.com/R-users-DC/" target="_blank" rel="noopener">R Meetup</a>, but nothing like the <a href="http://www.meetup.com/NYC-Predictive-Analytics/" target="_blank" rel="noopener">NYC Predictive Analytics Meetup</a>. So, I and a couple of others I talked to about this (<a title="Marck's LinkedIn page" href="http://www.linkedin.com/in/marckvaisman" target="_blank" rel="noopener">Marck Vaisman</a>, who I first met through the <a href="http://www.meetup.com/nyhackr/" target="_blank" rel="noopener">NYC R Meetup </a>a couple years ago, and <a title="Matt's LinkedIn profile" href="http://www.linkedin.com/pub/matthew-bryan/26/210/2a4" target="_blank" rel="noopener">Matt Bryan</a>, who I met just after moving to town), started a new Meetup, which we decided to call "<a href="http://www.meetup.com/Data-Science-DC/" target="_blank" rel="noopener">Data Science DC</a>".

For our second meetup, we thought we should address some aspect of our name, and so I presented a little bit about the term and the controversies around its definition and its recent dramatic upsurge in popularity. Here are the slides (note that you should be able to click through the links on the slide to the source documents):

<iframe src="https://docs.google.com/present/embed?id=dgxc9gbd_58c2j8vnrh&amp;size=m" width="555" height="451" frameborder="0"></iframe>

I mostly didn't present a personal opinion about what I though the term means, or what it should mean, but instead wanted to present a bunch of other peoples' points of view to kick off an interesting discussion. And in that sense I succeeded. We had an exceedingly interesting conversation following my slides, and I think a couple of the most interesting ideas from the evening came out of that discussion.

Here are three theses I'd like to propose.

* <strong>"Data Science" is defined as what "Data Scientists" do.</strong> <em>What</em> Data Scientists do has been <a href="http://www.dataists.com/2010/09/a-taxonomy-of-data-science/" target="_blank" rel="noopener">very</a> <a href="http://radar.oreilly.com/2010/06/what-is-data-science.html" target="_blank" rel="noopener">well</a> <a href="http://www.drewconway.com/zia/?p=2378" target="_blank" rel="noopener">covered</a>, and it runs the gamut from data collection and munging, through application of statistics and machine learning and related techniques, to interpretation, communication, and visualization of the results. <em>Who</em> Data Scientists are may be the more fundamental question.
* One reason Data Science is a big thing <em>now</em> is because <strong>advances in technology have made it easy for Data Scientists to develop wide-ranging expertise</strong>. Even 10 years ago, the idea that the same person could integrate several databases, run a multilevel regression, and generate elegant visualizations would be seen as incredibly rare.
* The other reason Data Science is a big thing <em>now</em> is because<strong> sabermetrics demonstrated that number-crunching brings results</strong>. There's nothing business leaders love more than a sports analogy, and the analytic revolution in professional sports immediately draw attention to the ways that numbers beat intuition.

I tend to like the idea that Data Science is defined by its practitioners, that it's a <a href="http://www.johndcook.com/blog/2011/08/18/jack-of-all-trades/" target="_blank" rel="noopener">career path </a>rather than a category of activities. In my conversations with people, it seems that people who consider themselves Data Scientists typically have eclectic career paths, that might in some ways seem <a href="http://www.ribbonfarm.com/2011/08/19/the-calculus-of-grit/" target="_blank" rel="noopener">not to make much sense</a>. A typical path might be someone who started out learning to program, then spent some time in a scientific field, then hopped around a variety of different roles, collecting a wide variety of different skills, all of which related to using analytical techniques to make sense of data.

This sort of career path isn't particularly new, but what is new is that it's now possible to relatively quickly and cheaply do get started in all of the processes involved in Data Science. (Thanks to Taylor Horton for suggesting this at the Meetup!) Fast computers, open source tools, and some programming skills allow someone to try a new data management approach or a new machine learning technology incredibly quickly, and to iterate on approaches until a solution to a particular problem is found. This has two consequences. First of all, the productivity of a modern Data Scientist is remarkable. Projects that a few decades ago would have taken teams of people literally years can now be done in a few days. Second of all, this amazing productivity allows people to spend their <a title="PDF" href="http://www.coachingmanagement.nl/The%20Making%20of%20an%20Expert.pdf" target="_blank" rel="noopener">10,000 hours developing expertise</a> in the now vertically integrated process of Data Science, rather than having to spend all of that time focusing on developing skills on just a single aspect of the task. There are huge number of things that need to be learned to be an effective Data Scientist, but it is now possible to learn those skills quickly enough to make a career out of being a Jack of all Trades and a near-master at many of them.

So now there's a supply of people who could be Data Scientists. But what about the type of demand that drives an<a href="http://blogs.oreilly.com/cgi-bin/mt/mt-search.cgi?blog_id=57&amp;tag=data%20science&amp;limit=20&amp;IncludeBlogs=57" target="_blank" rel="noopener"> incessant stream of O'Reilly articles</a> and <a href="http://www.nytimes.com/2009/08/06/technology/06stats.html" target="_blank" rel="noopener">job postings</a>? Where does the demand come from? <a href="http://twitter.com/#!/justgrimes" target="_blank" rel="noopener">Justin Grimes </a>had an intriguing idea that resonated with me -- analytics in sports, which I propose as the other reason why analytics and data science have become buzzwords. Although <a href="http://en.wikipedia.org/wiki/Scientific_management" target="_blank" rel="noopener">business has used mathematical methods for 100 years</a>, (thousands if you include finance and insurance) the idea that you could hire a very small number of people to analyze data and beat gut instincts in many aspects of decision making is much newer. The idea that<a href="http://en.wikipedia.org/wiki/Moneyball" target="_blank" rel="noopener"> a statistician could turn around the Oakland A's</a> by radically overturning longstanding recruiting practice was a powerful analogy. Even now, <a href="http://www.amazon.com/Super-Crunchers-Thinking-Numbers-Smart/dp/0553805401" target="_blank" rel="noopener">business books about analytics almost always have sports examples in the first chapters</a>. I made a point at work the other day by noting that <a title="Freakanomics Radio on Prediction" href="http://www.wnyc.org/shows/freakonomics-radio/2011/jun/24/" target="_blank" rel="noopener">most professional sports prognosticators predict NFL playoff outcomes wrong because they over-weight last years' results</a>. Sports analogies get attention.

Does this make sense? Data Science is a buzzword now because a group of people with eclectic talents match a growing demand for and recognition of the value of those talents. I'd love feedback on these thoughts!


