---
title: INFORMS Business Analytics 2014 Blog Posts
author: ''
date: '2014-08-02'
slug: informs-business-analytics-2014-blog-posts
categories:
  - professional
tags:
  - analytics
  - data science
  - operations research
---

Earlier this year, I attended the <a href="http://meetings2.informs.org/analytics2014/" target="_blank" rel="noopener">INFORMS Conference on Business Analytics &amp; Operations Research</a>, in Boston. I was asked beforehand if I wanted to be a conference blogger, and for some reason I said I would. This meant I was able to publish posts on the conference's WordPress web site, and was also obliged to do so!

Here are the five posts that I wrote, along with an excerpt from each. Please click through to read the full pieces:
<h2><a href="http://meetings2.informs.org/wordpress/analytics2014/2014/03/30/operations-research-from-the-point-of-view-of-data-science/" target="_blank" rel="noopener">Operations Research, from the point of view of Data Science</a></h2>
<ul>
 * more insight, less action — deliverables tend towards predictions and storytelling, versus formal optimization</li>
 * more openness, less big iron — open source software leads to a low-cost, highly flexible approach</li>
 * more scruffy, less neat — data science technologies often come from black-box statistical models, vs. domain-based theory</li>
 * more velocity, smaller projects — a hundred $10K projects beats one $1M project</li>
 * more science, less engineering — both practitioners and methods have different backgrounds</li>
 * more hipsters, less suits — stronger connections to the tech industry than to the boardroom</li>
 * more rockstars, less teams — one person can now (roughly) do everything, in simple cases, for better or worse</li>
</ul>
<h2><a href="http://meetings2.informs.org/wordpress/analytics2014/2014/03/31/what-is-a-data-product/" target="_blank" rel="noopener">What is a “Data Product”?</a></h2>
<p style="padding-left: 30px;">DJ Patil says “a data product is a product that facilitates an end goal through the use of data.” So, it’s not just an analysis, or a recommendation to executives, or an insight that leads to an improvement to a business process. It’s a visible component of a system. LinkedIn’s People You May Know is viewed by many millions of customers, and it’s based on the complex interactions of the customers themselves.</p>

<h2><a href="http://meetings2.informs.org/wordpress/analytics2014/2014/04/01/healthcare-and-not-education-at-informs-analytics/" target="_blank" rel="noopener">Healthcare (and not Education) at INFORMS Analytics</a></h2>
<p style="padding-left: 30px;">[A]s a DC resident, we often hear of “Healthcare and Education” as a linked pair of industries. Both are systems focused on social good, with intertwined government, nonprofit, and for-profit entities, highly distributed management, and (reportedly) huge opportunities for improvement. Aside from MIT Leaders for Global Operations winning the Smith Prize (and a number of shoutouts to academic partners and mentors), there was not a peep from the education sector at tonight’s awards ceremony. Is education, and particularly K-12 and postsecondary education, not amenable to OR techniques or solutions?</p>

<h2><a href="http://meetings2.informs.org/wordpress/analytics2014/2014/04/01/whats-changed-at-the-practiceanalytics-conference/" target="_blank" rel="noopener">What’s Changed at the Practice/Analytics Conference?</a></h2>
<p style="padding-left: 30px;"><span style="color: #444444;">In 2011, almost every talk seemed to me to be from a Fortune 500 company, or a large nonprofit, or a consulting firm advising a Fortune 500 company or a large nonprofit. Entrepeneurship around analytics was barely to be seen. This year, there are at least a few talks about Hadoop and iPhone apps and more. Has the cost of deploying advanced analytics substantially dropped?</span></p>

<h2><a href="http://meetings2.informs.org/wordpress/analytics2014/2014/04/01/why-oranalytics-people-need-to-know-about-database-technology/" target="_blank" rel="noopener">Why OR/Analytics People Need to Know About Database Technology</a></h2>
<p style="padding-left: 30px;">It’s worthwhile learning a bit about databases, even if you have no decision-making authority in your organization, and don’t feel like becoming a database administrator (good call). But by getting involved early in the data-collection process, when IT folks are sitting around a table arguing about platform questions, you can get a word in occasionally about the things that matter for analytics — collecting all the data, storing it in a way friendly to later analytics, and so forth.</p>
All in all, I enjoyed blogging the conference, and recommend the practice to others! It's a great way to organize your thoughts and to summarize and synthesize your experiences.
